language: python
cache: pip
python:
  - 3.5
  - 3.6
env:
  - LOGGING=info
install:
  - apt install libopenblas-dev
  - pip install -r requirements.txt
  - pip install pytest pytest-cov wheel codecov
  - python setup.py bdist_wheel
  - pip install dist/dc_qiskit_qml*.whl
script:
  - make coverage
after_success:
  - codecov
