language: python
cache: pip
python:
  - 3.5
  - 3.6
env:
  - LOGGING=info
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenblas-dev
  - pip install -r requirements.txt
  - ln -s /usr/lib/libopenblas.a $PWD/libopenblas.a
  - pip install pytest pytest-cov wheel codecov
install:
  - python setup.py bdist_wheel
  - pip install dist/dc_qiskit_qml*.whl
script:
  - ls -la
  - make coverage
after_success:
  - codecov
