language: python
cache: pip
python:
  - 3.5
  - 3.6
env:
  - LOGGING=info
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenblas-dev
  - ls -la /usr/lib | grep blas
  - pip install -r requirements.txt
  - ln -s /usr/lib/libopenblas.a $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")/libopenblas.a
  - pip install pytest pytest-cov wheel codecov
install:
  - python setup.py bdist_wheel
  - pip install dist/dc_qiskit_qml*.whl
script:
  - ls -la
  - make coverage
after_success:
  - codecov
