language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env:
  - LOGGING=info
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install g++-7
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libopenblas-dev
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade pytest pytest-cov wheel codecov
install:
  - python setup.py bdist_wheel
  - pip install dist/dc_qiskit_qml*.whl
script:
  - ls -la
  - make coverage
after_success:
  - codecov
